### ISSUE TITLE
TypeError: Cannot read property 'slug' of undefined - Relates to post tags in dashboard home

### ISSUE THREAD

**Issue by ronilaukkarinen** [themeblvd/justwrite#24]
Hello! I love the concept! However, justwrite.app doesn't open the dashboard. I can get the single articles visible by opening manually for example http://justwrite.app/edit/189. But going to http://justwrite.app just shows blank page and this in Console:

````
app.js:63 TypeError: Cannot read property 'slug' of undefined
    at app.js:38
    at Array.map (<anonymous>)
    at app.js:38
    at beginWork (app.js:63)
    at o (app.js:63)
    at i (app.js:63)
    at b (app.js:63)
    at A (app.js:63)
    at v (app.js:63)
    at m (app.js:63)
````

**Comment by themeblvd** [comment]
What web browser is this happening in?

**Comment by themeblvd** [comment]
Hm, very strange. I can’t reproduce on my end. But from the error it appears to be something related to getting the list of tags for posts in the dashboard. 

Are you using the sandbox demo site? Or did you put in a URL to your own site to pull data from?

**Comment by ronilaukkarinen** [comment]
I put the URL to my own site. I have 1500+ articles on that site, perhaps some of those is causing it? oh and the website is in Finnish. There are drafts as well.

**Comment by themeblvd** [comment]
Thank you for starting this issue. I think I know what the problem is. And it's very useful for me to know.

If your site has 1500 posts, I would guess you also have a lot of post tags. So assuming this, in short, when Just Write attempts to get "all" tags of your website, because you have so many, it's not getting all of them (this is my guess, anyway). I'll explain if you're interested --

When you retrieve a post from WordPress, it has a "tags" attribute which contains an array of tag ids, like `[1, 2,  3, 4]`. But from that, we don't know anything else about the tags (i.e. like what the corresponding tags slug/names are like `foo`, `bar`, etc). So Just Write then has to do a separate query out to your website to get all of the post tags,  which are stored in a different table of your site's database.

Then when displaying the list of tags for an individual post, it has to loop through the given IDs and for each, it finds the matching tag information from the global tags, which were all queried separately from the posts. -- Otherwise, a query to your server would have to be performed for each and every tag, in each and every post to display, which wouldn't make sense.

If you see here: https://github.com/themeblvd/justwrite/blob/master/src/components/TagList.js

... That's where Just Write is listing the tags, when displaying each individual post. You can see that for each tag ID it's given for the current post, it *assumes* it has a matching tag in the global tags list.

Because the feature of displaying tags for posts on the main dashboard page isn't a necessity, I don't think it makes sense to attempt to pull all tags from a WordPress site, in the event it has many, many tags. Instead, when displaying tags of a post, I just need to make sure there's some simple check that a tag ID for the given post has a corresponding tag currently available within the Just Write application. And if not, just skip it.

**Comment by ronilaukkarinen** [comment]
Ok, cool! glad to hear this was useful. If you need any more details from me, let me know. I'm so excited about this project.

**Comment by monecchi** [comment]
Hi there.  I've just tried Just Write (great concept by the way) and I connected to a site which tags are not so many ( around +100 ) but the issue described here persists.

**Comment by themeblvd** [comment]
@monecchi I actually had never gotten a chance to get to it; so thanks for reminding me. I believe I have it sorted now, and I've posted the latest version to the demo at justwrite.app. Clear your browser cache and give it another try.

When fixing, I realized that when the application queries tags, authors, and categories, it doesn't specify any amount and so WP will return up to 10 by default. So in theory, previously the dashboard could fail if you had more than 10 tags on your site. It will now query up to 100 tags, and if you have more than that, they should gracefully just not display in the dashboard, with no errors.

**Comment by monecchi** [comment]
Hey @themeblvd, thanks for following up and having the issue fixed. I can confirm it works flawlessly now. I randomly came across a post about JustWrite on WP Tavern and I should say I'm amazed to have discovered such a well craft project here on github!

I've been learning how to take the most out of WP REST API + React and I hope to have my skills improved by learning with your project.

Congratulations for such a beautiful work!
